server:
  port: 8090

#spring:
#  application:
#    name: api-gateway
#  cloud:
#    gateway:
#      routes:
#        - id: account-service
#          uri: http://localhost:8081
#          predicates:
#            - Path=/accounts/**
#        - id: card-service
#          uri: http://localhost:8083
#          predicates:
#            - Path=/cards/**
#        - id: loans-service
#          uri: http://localhost:8082
#          predicates:
#            - Path=/loans/**

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: account-service
          uri: lb://account-service
          predicates:
            - Path=/accounts/**
        - id: card-service
          uri: lb://card-service
          predicates:
            - Path=/cards/**
        - id: loans-service
          uri: lb://loans-service
          predicates:
            - Path=/loans/**


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    initial-instance-info-replication-interval-seconds: 10
    register-with-eureka: true
    fetch-registry: true
    instance:
      prefer-ip-address: true
    instance-id: api-gateway:${server.port}